var data = {
    characters: [
        'Human Male Soldier',
        'Human Male Vanguard',
        'Human Male Engineer',
        'Human Male Sentinel',
        'Human Male Adept',
        'Human Male Infiltrator',
        'Human Female Soldier',
        'Human Female Vanguard',
        'Human Female Engineer',
        'Human Female Sentinel',
        'Human Female Adept',
        'Human Female Infiltrator',
        'Turian Soldier',
        'Krogan Vanguard',
        'Krogan Engineer',
        'Asari Sentinel',
        'Salarian Infiltrator',
        'Asari Adept',
        'Krogan Mercenary',
        'Turian Havoc Trooper',
        'Asari Huntress',
        'Angara Insurgent',
        'Salarian Architect',
        'Asari Duelist',
        'Angara Avenger',
        'Salarian Operator',
        'Human Kineticist',
        'Krogan Gladiator'
    ],
    weapons: [
        'Viper',
        'Avenger',
        'Charger',
        'Predator',
        'Katana',
        'Carnifex',
        'Cyclone',
        'Disciple',
        'Incisor',
        'M-5 Phalanx',
        'M-96 Mattock',
        'Raptor',
        'Ruzad',
        'Widow',
        'Zalkin',
        'Equalizer',
        'Hesh',
        'Isharay',
        'L-89 Halberd',
        'Lanat',
        'M-25 Hornet',
        'M-37 Falcon',
        'M-90 Indra',
        'Revenant',
        'Sandstorm',
        'Scattershot',
        'Scorpion',
        'Shadow',
        'Sidewinder',
        'Sweeper',
        'Talon',
        'Thokin',
        'Vanquisher',
        'Venom',
        'Black Widow',
        'Dhan',
        'Inferno',
        'N7 Crusader',
        'N7 Eagle',
        'N7 Hurricane',
        'N7 Piranha',
        'N7 Valiant',
        'N7 Valkyrie',
        'Naladen',
        'P.A.W.',
        'Rozerad',
        'Soned',
        'Ushior'
    ]
};

export default data;